[model]
inference_profile = "us.anthropic.claude-sonnet-4-20250514-v1:0"
model_id = "anthropic.claude-sonnet-4-20250514-v1:0"
model_regions = ["us-west-2", "us-east-1", "us-east-2", "us-west-1"]

[inference_config]
anthropic_version = "bedrock-2023-05-31"
max_tokens = 4096
temperature = 0.0
top_k = 128
top_p = 0.9
stop_sequences = ["\n\nHuman"]
